version: '3.9'
services:
  front:
    restart: on-failure
    build: ./frontend
    environment:
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
    ports:
      - '3000:3000'
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - front